### ISSUE TITLE
关于图片替换的问题·

### ISSUE THREAD

**Issue by tx123456** [wuapnjie/PuzzleView#17]
我在我的项目中使用我自己的图片选择图片选择图片替换，选择完成后一点反应也没有，但是如果用你demo中的那个图片选择库选择图片就可以替换成功，我在代码中打了断点，两个图片选择库连获取的图片路径都是一样的，不知道是什么原因

**Comment by tx123456** [comment]
找到原因了，是因为glide图片加载的问题，这是我图片加载的方法

 final SimpleTarget<Bitmap> target = new SimpleTarget<Bitmap>() {
                    @Override
                    public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                        mPuzzleView.replace(resource);
                    }
                };
                Glide.with(MokaActivity.this).load(path).asBitmap().into(target);

下面是错误日志
 Process: com.example.tanxin.mokademo, PID: 23860
                  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
                      at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
                      at android.os.Handler.handleCallback(Handler.java:815)
                      at android.os.Handler.dispatchMessage(Handler.java:104)
                      at android.os.Looper.loop(Looper.java:194)
                      at android.app.ActivityThread.main(ActivityThread.java:5875)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1119)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)
                   Caused by: java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
                      at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:134)
                      at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:102)
                      at com.bumptech.glide.Glide.with(Glide.java:653)
                      at com.example.tanxin.mokademo.MokaActivity$5.onSelectSuccess(MokaActivity.java:207)
                      at com.luck.picture.lib.ui.PictureImageGridActivity.onResult(PictureImageGridActivity.java:838)
                      at com.luck.picture.lib.ui.PictureImageGridActivity$2.onCompressSuccess(PictureImageGridActivity.java:959)
                      at com.luck.picture.lib.compress.LuBanCompress$1.onSuccess(LuBanCompress.java:75)
                      at com.luck.picture.lib.compress.Luban$1.onNext(Luban.java:164)
                      at com.luck.picture.lib.compress.Luban$1.onNext(Luban.java:156)
                      at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:198)
                      at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:250)
                      at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                      at android.os.Handler.handleCallback(Handler.java:815) 
                      at android.os.Handler.dispatchMessage(Handler.java:104) 
                      at android.os.Looper.loop(Looper.java:194) 
                      at android.app.ActivityThread.main(ActivityThread.java:5875) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1119) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885) 


我应该怎样去加载它

**Comment by wuapnjie** [comment]
你不用管怎么加载，重要的是怎么获取bitmap，看错误原因是给Glide传了一个被销毁的Activity

2017年5月22日 22:04，"Tanx" <notifications@github.com>写道：

找到原因了，是因为glide图片加载的问题，这是我图片加载的方法

final SimpleTarget target = new SimpleTarget() {
@override <https://github.com/override>
public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap>
glideAnimation) {
mPuzzleView.replace(resource);
}
};
Glide.with(MokaActivity.this).load(path).asBitmap().into(target);

下面是错误日志
Process: com.example.tanxin.mokademo, PID: 23860
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(
HandlerScheduler.java:111)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5875)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(
ZygoteInit.java:1119)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)
Caused by: java.lang.IllegalArgumentException: You cannot start a load for
a destroyed activity
at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(
RequestManagerRetriever.java:134)
at com.bumptech.glide.manager.RequestManagerRetriever.get(
RequestManagerRetriever.java:102)
at com.bumptech.glide.Glide.with(Glide.java:653)
at com.example.tanxin.mokademo.MokaActivity$5.onSelectSuccess(MokaActivity.
java:207)
at com.luck.picture.lib.ui.PictureImageGridActivity.onResult(
PictureImageGridActivity.java:838)
at com.luck.picture.lib.ui.PictureImageGridActivity$2.onCompressSuccess(
PictureImageGridActivity.java:959)
at com.luck.picture.lib.compress.LuBanCompress$1.onSuccess(
LuBanCompress.java:75)
at com.luck.picture.lib.compress.Luban$1.onNext(Luban.java:164)
at com.luck.picture.lib.compress.Luban$1.onNext(Luban.java:156)
at io.reactivex.internal.operators.observable.ObservableObserveOn$
ObserveOnObserver.drainNormal(ObservableObserveOn.java:198)
at io.reactivex.internal.operators.observable.ObservableObserveOn$
ObserveOnObserver.run(ObservableObserveOn.java:250)
at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(
HandlerScheduler.java:109)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5875)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(
ZygoteInit.java:1119)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)

我应该怎样去加载它

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/wuapnjie/PuzzleView/issues/17#issuecomment-303109542>,
or mute the thread
